// Medical Affairs Copilot — Orchestrator demo data (plain script -> window.ORCH)
window.ORCH = {
  // ---------------------------------------------------------------- protocol
  protocol: {
    id: 'RSV-PreF-301',
    nct: 'NCT05••••421',
    title: 'A Phase 3 Study of a Bivalent RSV Prefusion-F Vaccine in Adults Aged ≥60',
    sponsor: 'Veritan Biologics',
    phase: '3',
    indication: 'Respiratory Syncytial Virus — lower respiratory tract disease (LRTD)',
    intervention: 'Bivalent RSV prefusion-F subunit vaccine · single intramuscular dose',
    modality: 'Recombinant subunit (stabilized prefusion F antigen, AS01-adjuvanted)',
    population: 'Community-dwelling, immunocompetent adults aged ≥60',
    enrollment: '24,800',
    geographies: ['US', 'EU', 'JP', 'AU'],
    specialties: ['Vaccinology', 'Infectious Disease', 'Geriatric Medicine', 'Pulmonology'],
    themes: ['Prefusion-F immunogenicity', 'Older-adult LRTD prevention', 'Reactogenicity in ≥60', 'Durability of protection'],
    status: 'Ready for review',
    updated: '2026-06-06 09:42 UTC',
    run: 'run_8f2a91',
  },

  // ---------------------------------------------------------------- stages
  stages: [
    { key: 'parsed',   label: 'Parsed',           state: 'done',    detail: '312 chunks' },
    { key: 'brief',    label: 'Brief Extracted',  state: 'done',    detail: '12 sections' },
    { key: 'queries',  label: 'Queries Generated',state: 'done',    detail: '7 groups' },
    { key: 'evidence', label: 'Evidence Retrieved',state: 'done',   detail: '148 sources' },
    { key: 'kols',     label: 'KOLs Extracted',   state: 'done',    detail: '64 candidates' },
    { key: 'ranked',   label: 'Ranked',           state: 'done',    detail: '64 scored' },
    { key: 'moss',     label: 'Indexed in Moss',  state: 'warn',    detail: '3 retrying' },
    { key: 'review',   label: 'Ready for Review',  state: 'active',  detail: 'Awaiting sign-off' },
  ],

  // ---------------------------------------------------------------- status cards
  statusCards: [
    { key: 'kols',     label: 'KOLs found',              value: '64',   sub: '18 shortlisted', tone: 'accent',     icon: 'users' },
    { key: 'evidence', label: 'Evidence sources',        value: '148',  sub: 'across 6 source types', tone: 'evidence', icon: 'evidence' },
    { key: 'missing',  label: 'Missing-data warnings',   value: '5',    sub: '2 affect ranking', tone: 'compliance', icon: 'alert' },
    { key: 'flags',    label: 'Compliance flags',        value: '2',    sub: 'open · reviewer required', tone: 'risk', icon: 'shield' },
    { key: 'moss',     label: 'Moss index',              value: '97%',  sub: '3 chunks retrying', tone: 'compliance', icon: 'database' },
  ],

  // ---------------------------------------------------------------- protocol brief
  brief: [
    { section: 'Study title',  value: 'A Phase 3 Study of a Bivalent RSV Prefusion-F Vaccine in Adults Aged ≥60', confidence: 99, chunk: '§1.1 / p.1', status: 'validated' },
    { section: 'Sponsor',      value: 'Veritan Biologics', confidence: 98, chunk: 'Title page', status: 'validated' },
    { section: 'Phase',        value: 'Phase 3', confidence: 99, chunk: '§1.2 / p.2', status: 'validated' },
    { section: 'Indication',   value: 'Respiratory Syncytial Virus — lower respiratory tract disease (LRTD)', confidence: 96, chunk: '§2.1 / p.4', status: 'validated' },
    { section: 'Intervention', value: 'Bivalent RSV prefusion-F subunit vaccine, single intramuscular dose', confidence: 95, chunk: '§3.2 / p.9', status: 'validated' },
    { section: 'Mechanism / modality', value: 'Recombinant subunit; stabilized prefusion F antigen, AS01-adjuvanted', confidence: 81, chunk: '§3.3 / p.10', status: 'review' },
    { section: 'Patient population', value: 'Community-dwelling, immunocompetent adults aged ≥60', confidence: 94, chunk: '§4.1 / p.13', status: 'validated' },
    { section: 'Inclusion criteria', value: 'Age ≥60; medically stable per investigator; able to consent', confidence: 92, chunk: '§4.2 / p.14', status: 'validated', list: true },
    { section: 'Exclusion criteria', value: 'Prior RSV vaccination; immunocompromise; acute febrile illness ≤72h', confidence: 90, chunk: '§4.3 / p.15', status: 'validated', list: true },
    { section: 'Primary endpoint', value: 'Vaccine efficacy against RSV-confirmed LRTD (≥2 lower-respiratory signs)', confidence: 97, chunk: '§6.1 / p.22', status: 'validated' },
    { section: 'Secondary endpoints', value: 'Neutralizing titers at day 30; safety & reactogenicity through 6 months', confidence: 88, chunk: '§6.2 / p.23', status: 'review' },
    { section: 'Geography', value: 'United States, European Union, Japan, Australia', confidence: 86, chunk: '§5.4 / p.19', status: 'validated' },
    { section: 'Relevant specialties', value: 'Vaccinology · Infectious Disease · Geriatric Medicine · Pulmonology', confidence: 72, chunk: 'Derived', status: 'review', derived: true },
    { section: 'Scientific themes', value: 'Prefusion-F immunogenicity · older-adult LRTD prevention · reactogenicity · durability', confidence: 68, chunk: 'Derived', status: 'review', derived: true },
  ],

  // ---------------------------------------------------------------- search queries
  queryGroups: [
    { id: 'g1', name: 'Disease state + trial investigator', status: 'approved', results: 41,
      sources: ['ClinicalTrials.gov', 'PubMed'],
      queries: ['"RSV" AND "lower respiratory tract disease" AND principal investigator', 'RSV prefusion vaccine trial investigator adults ≥60'] },
    { id: 'g2', name: 'Disease state + Phase 3 investigator', status: 'approved', results: 28,
      sources: ['ClinicalTrials.gov'],
      queries: ['RSV vaccine "Phase 3" investigator older adults', 'respiratory syncytial virus Phase III site PI'] },
    { id: 'g3', name: 'Intervention class + publication author', status: 'edited', results: 53,
      sources: ['PubMed'],
      queries: ['prefusion F subunit vaccine author[full]', 'AS01 adjuvant RSV immunogenicity author'] },
    { id: 'g4', name: 'Endpoint keywords + expert', status: 'approved', results: 34,
      sources: ['PubMed', 'Congress pages'],
      queries: ['"neutralizing titers" RSV day 30 expert', 'RSV-confirmed LRTD efficacy endpoint author'] },
    { id: 'g5', name: 'Guideline authors', status: 'approved', results: 12,
      sources: ['Society / guidelines'],
      queries: ['ACIP RSV older adults recommendation author', 'WHO / national RSV immunization guideline contributor'] },
    { id: 'g6', name: 'Congress speakers', status: 'regenerating', results: null,
      sources: ['Congress pages'],
      queries: ['IDWeek RSV session speaker 2024–2025', 'ESWI RSV symposium faculty'] },
    { id: 'g7', name: 'Institution leaders', status: 'disabled', results: 0,
      sources: ['Institutional bios'],
      queries: ['vaccinology department chair RSV program', 'infectious disease division head clinical trials'] },
  ],
  querySources: [
    { name: 'ClinicalTrials.gov', count: 38, state: 'ok' },
    { name: 'PubMed', count: 71, state: 'ok' },
    { name: 'Institutional bios', count: 14, state: 'partial' },
    { name: 'Society / guidelines', count: 9, state: 'ok' },
    { name: 'Congress pages', count: 16, state: 'running' },
    { name: 'Transparency / payments', count: 0, state: 'off' },
  ],

  // ---------------------------------------------------------------- evidence
  evidence: [
    { id: 'e1', type: 'Publication', title: 'Efficacy of a bivalent RSV prefusion F vaccine in older adults', host: 'N Engl J Med', url: 'nejm.org/doi/10.1056/NEJMoa24•••', date: '2024-03', score: 96, geo: 'EU', specialty: 'Vaccinology', strength: 'strong', snippet: 'A single dose conferred 82.6% efficacy against RSV-confirmed LRTD with ≥2 signs in adults aged 60 years or older.', entities: ['E. Marchetti', 'RSV-PreF', 'LRTD'], kols: ['marchetti'] },
    { id: 'e2', type: 'Publication', title: 'Neutralizing antibody responses to RSV prefusion F immunization', host: 'Lancet Infect Dis', url: 'thelancet.com/journals/laninf/•••', date: '2023-11', score: 91, geo: 'APAC', specialty: 'Infectious Disease', strength: 'strong', snippet: 'Day-30 neutralizing titers rose 14.2-fold against RSV-A and 10.7-fold against RSV-B subgroups.', entities: ['H. Tanaka', 'neutralizing titers', 'day 30'], kols: ['tanaka', 'marchetti'] },
    { id: 'e3', type: 'Trial registry', title: 'Phase 3 RSV prefusion-F efficacy study — site investigators', host: 'ClinicalTrials.gov', url: 'clinicaltrials.gov/study/NCT04•••', date: '2022-08', score: 89, geo: 'US', specialty: 'Vaccinology', strength: 'strong', snippet: 'Listed as coordinating principal investigator across 14 EU sites for the pivotal efficacy cohort.', entities: ['E. Marchetti', 'PI', 'Phase 3'], kols: ['marchetti'] },
    { id: 'e4', type: 'Guideline', title: 'Immunization of older adults against RSV — advisory statement', host: 'ACIP / society', url: 'cdc.gov/vaccines/acip/•••', date: '2024-06', score: 84, geo: 'US', specialty: 'Geriatric Medicine', strength: 'moderate', snippet: 'Contributing author to the working group recommendation on RSV vaccination for adults ≥60.', entities: ['A. Okonkwo', 'guideline', '≥60'], kols: ['okonkwo'] },
    { id: 'e5', type: 'Congress', title: 'IDWeek 2025 — RSV in the aging immune system (symposium)', host: 'IDWeek', url: 'idweek.org/program/•••', date: '2025-10', score: 78, geo: 'US', specialty: 'Infectious Disease', strength: 'moderate', snippet: 'Invited faculty; presented on immunosenescence and prefusion-F durability in older adults.', entities: ['H. Tanaka', 'symposium', 'durability'], kols: ['tanaka'] },
    { id: 'e6', type: 'Publication', title: 'Safety and reactogenicity of subunit RSV vaccines in the elderly', host: 'Clin Infect Dis', url: 'academic.oup.com/cid/•••', date: '2022-05', score: 80, geo: 'US', specialty: 'Geriatric Medicine', strength: 'moderate', snippet: 'Local and systemic reactogenicity were transient; no safety signal in the ≥70 subgroup.', entities: ['A. Okonkwo', 'reactogenicity', 'safety'], kols: ['okonkwo'] },
    { id: 'e7', type: 'Institutional', title: 'Karolinska Institutet — Department of Vaccinology faculty bio', host: 'ki.se', url: 'ki.se/en/people/•••', date: '2025-01', score: 64, geo: 'EU', specialty: 'Vaccinology', strength: 'weak', snippet: 'Professor of Vaccinology; leads the respiratory virus immunology group.', entities: ['E. Marchetti', 'Karolinska'], kols: ['marchetti'] },
    { id: 'e8', type: 'Publication', title: 'Durability of prefusion-F immune responses over 24 months', host: 'Vaccine', url: 'sciencedirect.com/vaccine/•••', date: '2025-02', score: 87, geo: 'EU', specialty: 'Vaccinology', strength: 'strong', snippet: 'Titers remained above baseline at 24 months, informing booster-interval modeling.', entities: ['L. Andersson', 'durability', 'booster'], kols: ['andersson'] },
    { id: 'e9', type: 'Trial registry', title: 'Adult RSV vaccine immunogenicity study — Japan cohort', host: 'ClinicalTrials.gov', url: 'clinicaltrials.gov/study/NCT05•••', date: '2023-03', score: 83, geo: 'APAC', specialty: 'Infectious Disease', strength: 'moderate', snippet: 'National coordinating investigator for the Japanese immunogenicity sub-study.', entities: ['H. Tanaka', 'Japan', 'immunogenicity'], kols: ['tanaka'] },
    { id: 'e10', type: 'Publication', title: 'Pulmonary outcomes after RSV-LRTD in community-dwelling seniors', host: 'Am J Respir Crit Care Med', url: 'atsjournals.org/•••', date: '2024-09', score: 79, geo: 'US', specialty: 'Pulmonology', strength: 'moderate', snippet: 'Characterized lower-respiratory sequelae relevant to the protocol primary endpoint definition.', entities: ['M. Delacroix', 'LRTD', 'pulmonary'], kols: ['delacroix'] },
  ],
  evidenceFilters: {
    type: ['Publication', 'Trial registry', 'Guideline', 'Congress', 'Institutional'],
    geo: ['US', 'EU', 'APAC'],
    strength: ['strong', 'moderate', 'weak'],
  },

  // ---------------------------------------------------------------- candidates
  candidates: [
    { id: 'marchetti', rank: 1, name: 'Dr. Elena Marchetti', institution: 'Karolinska Institutet', specialty: 'Vaccinology', geo: 'EU · Sweden',
      trial: 'lead', pubRel: 96, influence: 'high', sources: 37, flags: 0, status: 'validated', score: 92.4,
      title: 'Professor of Vaccinology', location: 'Stockholm, Sweden',
      breakdown: [
        { label: 'Protocol match', value: 19.2, max: 20 },
        { label: 'Trial investigator experience', value: 24.0, max: 25 },
        { label: 'Publication relevance', value: 18.5, max: 20 },
        { label: 'Institution / site relevance', value: 9.4, max: 10 },
        { label: 'Guideline / congress influence', value: 12.8, max: 15 },
        { label: 'Recency', value: 8.5, max: 10 },
      ],
      rationale: 'Direct Phase 3 prefusion-F trial leadership; authored evidence on the protocol’s primary efficacy endpoint in adults ≥60.',
      evidence: ['e1', 'e3', 'e7', 'e2'] },
    { id: 'tanaka', rank: 2, name: 'Prof. Hideo Tanaka', institution: 'University of Tokyo', specialty: 'Infectious Disease', geo: 'APAC · Japan',
      trial: 'investigator', pubRel: 94, influence: 'high', sources: 29, flags: 1, status: 'review', score: 88.1,
      title: 'Professor of Infectious Diseases', location: 'Tokyo, Japan',
      breakdown: [
        { label: 'Protocol match', value: 18.1, max: 20 },
        { label: 'Trial investigator experience', value: 20.0, max: 25 },
        { label: 'Publication relevance', value: 19.0, max: 20 },
        { label: 'Institution / site relevance', value: 8.6, max: 10 },
        { label: 'Guideline / congress influence', value: 13.4, max: 15 },
        { label: 'Recency', value: 9.0, max: 10 },
      ],
      rationale: 'Related Phase 3 trial experience in adult RSV; strong recent publication record on the immunogenicity endpoint.',
      evidence: ['e2', 'e5', 'e9'] },
    { id: 'okonkwo', rank: 3, name: 'Dr. Amara Okonkwo', institution: 'Johns Hopkins', specialty: 'Geriatric Medicine', geo: 'US',
      trial: 'investigator', pubRel: 88, influence: 'high', sources: 22, flags: 0, status: 'validated', score: 84.6,
      title: 'Associate Professor of Medicine', location: 'Baltimore, USA',
      breakdown: [
        { label: 'Protocol match', value: 17.4, max: 20 },
        { label: 'Trial investigator experience', value: 17.5, max: 25 },
        { label: 'Publication relevance', value: 17.6, max: 20 },
        { label: 'Institution / site relevance', value: 9.0, max: 10 },
        { label: 'Guideline / congress influence', value: 14.1, max: 15 },
        { label: 'Recency', value: 9.0, max: 10 },
      ],
      rationale: 'Authored geriatric immunization guidance directly relevant to the ≥60 population; active in related LRTD research.',
      evidence: ['e4', 'e6'] },
    { id: 'andersson', rank: 4, name: 'Dr. Lars Andersson', institution: 'Lund University', specialty: 'Vaccinology', geo: 'EU · Sweden',
      trial: 'investigator', pubRel: 85, influence: 'medium', sources: 19, flags: 0, status: 'validated', score: 81.2,
      title: 'Senior Lecturer, Vaccinology', location: 'Lund, Sweden',
      breakdown: [
        { label: 'Protocol match', value: 16.8, max: 20 },
        { label: 'Trial investigator experience', value: 16.0, max: 25 },
        { label: 'Publication relevance', value: 18.0, max: 20 },
        { label: 'Institution / site relevance', value: 8.0, max: 10 },
        { label: 'Guideline / congress influence', value: 11.4, max: 15 },
        { label: 'Recency', value: 11.0, max: 15 },
      ],
      rationale: 'Authored durability and booster-interval modeling for prefusion-F responses relevant to the protocol.',
      evidence: ['e8'] },
    { id: 'delacroix', rank: 5, name: 'Prof. Marie Delacroix', institution: 'Institut Pasteur', specialty: 'Pulmonology', geo: 'EU · France',
      trial: 'none', pubRel: 79, influence: 'medium', sources: 14, flags: 1, status: 'review', score: 76.8,
      title: 'Professor of Respiratory Medicine', location: 'Paris, France',
      breakdown: [
        { label: 'Protocol match', value: 15.0, max: 20 },
        { label: 'Trial investigator experience', value: 12.0, max: 25 },
        { label: 'Publication relevance', value: 16.5, max: 20 },
        { label: 'Institution / site relevance', value: 7.8, max: 10 },
        { label: 'Guideline / congress influence', value: 10.5, max: 15 },
        { label: 'Recency', value: 8.0, max: 10 },
      ],
      rationale: 'Characterized lower-respiratory sequelae relevant to the primary endpoint definition; no direct trial role found.',
      evidence: ['e10'] },
    { id: 'reyes', rank: 6, name: 'Dr. Sofia Reyes', institution: 'Hospital Clínic Barcelona', specialty: 'Infectious Disease', geo: 'EU · Spain',
      trial: 'investigator', pubRel: 74, influence: 'medium', sources: 12, flags: 0, status: 'validated', score: 73.5,
      title: 'Attending, Infectious Diseases', location: 'Barcelona, Spain',
      breakdown: [], rationale: 'Site investigator on adjacent adult RSV immunogenicity work in the EU region.', evidence: [] },
    { id: 'nakamura', rank: 7, name: 'Dr. Kenji Nakamura', institution: 'Osaka University', specialty: 'Vaccinology', geo: 'APAC · Japan',
      trial: 'none', pubRel: 71, influence: 'low', sources: 9, flags: 0, status: 'validated', score: 69.9,
      title: 'Associate Professor', location: 'Osaka, Japan',
      breakdown: [], rationale: 'Publication relevance to subunit adjuvant systems; limited recent trial activity.', evidence: [] },
    { id: 'mwangi', rank: 8, name: 'Dr. Grace Mwangi', institution: 'University of Melbourne', specialty: 'Geriatric Medicine', geo: 'AU',
      trial: 'investigator', pubRel: 68, influence: 'low', sources: 8, flags: 2, status: 'conflict', score: 66.2,
      title: 'Senior Research Fellow', location: 'Melbourne, Australia',
      breakdown: [], rationale: 'Related geriatric immunization research; transparency record requires reviewer attention.', evidence: [] },
  ],

  // ---------------------------------------------------------------- ranking
  rankingDimensions: [
    { key: 'match',     label: 'Protocol match',                weight: 0.20 },
    { key: 'trial',     label: 'Trial investigator experience', weight: 0.25 },
    { key: 'pub',       label: 'Publication relevance',         weight: 0.20 },
    { key: 'inst',      label: 'Institution / site relevance',  weight: 0.10 },
    { key: 'influence', label: 'Guideline / congress influence',weight: 0.15 },
    { key: 'recency',   label: 'Recency',                       weight: 0.10 },
  ],

  // ---------------------------------------------------------------- compliance
  guardrails: [
    { label: 'No promotional language', ok: true },
    { label: 'Do not rank by prescribing volume', ok: true },
    { label: 'No investigational safety / efficacy claims', ok: true },
    { label: 'Frame outreach as non-promotional scientific exchange', ok: true },
    { label: 'Every recommendation carries supporting evidence', ok: false },
  ],
  complianceFlags: [
    { id: 'c1', severity: 'high', kol: 'Dr. Grace Mwangi', type: 'Transparency / payment note', detail: 'Open Payments record indicates a consulting relationship in the indication area. Disclose and route to reviewer before any outreach.', status: 'open' },
    { id: 'c2', severity: 'medium', kol: 'Prof. Marie Delacroix', type: 'Missing source citation', detail: 'Ranking rationale references trial sequelae but the linked evidence count is 1 — below the 2-source threshold for an evidence-backed recommendation.', status: 'open' },
    { id: 'c3', severity: 'low', kol: 'Prof. Hideo Tanaka', type: 'Unsupported phrasing', detail: 'Draft brief used "leading expert" — rewritten to "scientifically relevant, evidence-supported" per scientific-exchange register.', status: 'resolved' },
  ],
  audit: [
    { time: '09:42:11', actor: 'system', text: 'Compliance scan completed — 2 open flags, 1 auto-resolved.' },
    { time: '09:41:03', actor: 'orchestrator', text: 'Ranking generated for 64 candidates; prescribing-volume signals excluded by policy.' },
    { time: '09:38:54', actor: 'system', text: 'Promotional-language filter applied to all generated rationales.' },
    { time: '09:30:22', actor: 'a.okoye (reviewer)', text: 'Approved protocol brief sections 1–9.' },
  ],

  // ---------------------------------------------------------------- moss index
  mossAssets: [
    { key: 'protocol', label: 'Protocol chunks',  chunks: 312, embedded: 312, failed: 0, state: 'done' },
    { key: 'evidence', label: 'Evidence chunks',  chunks: 148, embedded: 148, failed: 0, state: 'done' },
    { key: 'profiles', label: 'KOL profiles',     chunks: 64,  embedded: 61,  failed: 3, state: 'error' },
    { key: 'ranking',  label: 'Ranking metadata', chunks: 64,  embedded: 64,  failed: 0, state: 'done' },
    { key: 'cites',    label: 'Source citations', chunks: 148, embedded: 148, failed: 0, state: 'done' },
  ],
  mossFailed: [
    { id: 'f1', asset: 'KOL profile · Dr. Grace Mwangi', reason: 'Embedding timeout (provider 504)', attempts: 2 },
    { id: 'f2', asset: 'KOL profile · Dr. Sofia Reyes', reason: 'Source bio fetch blocked (robots)', attempts: 1 },
    { id: 'f3', asset: 'KOL profile · Dr. Kenji Nakamura', reason: 'Embedding timeout (provider 504)', attempts: 2 },
  ],
  mossSync: '2026-06-06 09:40 UTC',

  // ---------------------------------------------------------------- summary
  topKols: ['marchetti', 'tanaka', 'okonkwo'],
  warnings: [
    { text: 'Mechanism / modality extracted at 81% confidence — verify adjuvant detail against §3.3.', tone: 'compliance' },
    { text: 'Relevant specialties and scientific themes are derived, not stated in protocol.', tone: 'compliance' },
    { text: '3 KOL profiles not yet indexed in Moss (retrying).', tone: 'compliance' },
    { text: '1 candidate (Delacroix) below the 2-source evidence threshold.', tone: 'risk' },
    { text: '1 transparency / payment flag open (Mwangi).', tone: 'risk' },
  ],
  exports: [
    { fmt: 'PDF',  label: 'Review packet (PDF)', desc: 'Brief, top KOLs, evidence appendix, compliance notes.' },
    { fmt: 'CSV',  label: 'Candidates (CSV)',    desc: 'All 64 candidates with scores and source counts.' },
    { fmt: 'JSON', label: 'Structured export (JSON)', desc: 'Brief, queries, evidence, ranking, audit trail.' },
    { fmt: 'PKT',  label: 'Internal review packet', desc: 'Bundled artifacts for Medical Affairs sign-off.' },
  ],

  // ---------------------------------------------------------------- protocols list
  protocols: [
    { id: 'RSV-PreF-301', sponsor: 'Veritan Biologics', phase: '3', indication: 'RSV — LRTD', geo: 'US · EU · JP · AU', status: 'Ready for review', updated: '2 min ago', active: true },
    { id: 'ONC-KRAS-204', sponsor: 'Helix Oncology', phase: '2', indication: 'NSCLC (KRAS G12C)', geo: 'US · EU', status: 'Ranking', updated: '1 h ago', active: false },
    { id: 'NEU-AD-118',  sponsor: 'Cortexa Therapeutics', phase: '2', indication: 'Early Alzheimer’s', geo: 'US', status: 'Evidence retrieval', updated: '3 h ago', active: false },
    { id: 'IMM-PSO-330', sponsor: 'Aurelia Bio', phase: '3', indication: 'Plaque psoriasis', geo: 'EU · JP', status: 'Queued', updated: 'yesterday', active: false, empty: true },
  ],
  runs: [
    { id: 'run_8f2a91', protocol: 'RSV-PreF-301', started: '2026-06-06 09:12', duration: '30m', stage: 'Ready for review', state: 'warn', by: 'a.okoye' },
    { id: 'run_8f2a44', protocol: 'RSV-PreF-301', started: '2026-06-04 14:03', duration: '28m', stage: 'Completed', state: 'done', by: 'system' },
    { id: 'run_7c1e08', protocol: 'ONC-KRAS-204', started: '2026-06-06 08:20', duration: '—', stage: 'Ranking', state: 'active', by: 'm.singh' },
    { id: 'run_6b9d77', protocol: 'NEU-AD-118', started: '2026-06-06 06:55', duration: '—', stage: 'Evidence retrieval', state: 'active', by: 'system' },
    { id: 'run_5a4c12', protocol: 'RSV-PreF-301', started: '2026-05-29 11:40', duration: '31m', stage: 'Failed — parse error', state: 'error', by: 'a.okoye' },
  ],

  // ---------------------------------------------------------------- per-protocol header + stages
  // The selected protocol re-scopes the header, stage rail and every pipeline/governance screen.
  // Full demo data is wired for RSV-PreF-301; the others show their real in-flight run state.
  protocolDetails: {
    'RSV-PreF-301': {
      id: 'RSV-PreF-301', nct: 'NCT05••••421', run: 'run_8f2a91',
      title: 'A Phase 3 Study of a Bivalent RSV Prefusion-F Vaccine in Adults Aged ≥60',
      sponsor: 'Veritan Biologics', phase: '3', indication: 'RSV · LRTD', geo: ['US', 'EU', 'JP', 'AU'],
      enrollment: '24,800', status: 'Ready for review', statusTone: 'accent', updated: '2026-06-06 09:42 UTC',
      stages: [
        { key: 'parsed', label: 'Parsed', state: 'done', detail: '312 chunks' },
        { key: 'brief', label: 'Brief Extracted', state: 'done', detail: '12 sections' },
        { key: 'queries', label: 'Queries Generated', state: 'done', detail: '7 groups' },
        { key: 'evidence', label: 'Evidence Retrieved', state: 'done', detail: '148 sources' },
        { key: 'kols', label: 'KOLs Extracted', state: 'done', detail: '64 candidates' },
        { key: 'ranked', label: 'Ranked', state: 'done', detail: '64 scored' },
        { key: 'moss', label: 'Indexed in Moss', state: 'warn', detail: '3 retrying' },
        { key: 'review', label: 'Ready for Review', state: 'active', detail: 'Awaiting sign-off' },
      ],
    },
    'ONC-KRAS-204': {
      id: 'ONC-KRAS-204', nct: 'NCT06••••118', run: 'run_7c1e08',
      title: 'A Phase 2 Study of a KRAS G12C Inhibitor in Previously Treated NSCLC',
      sponsor: 'Helix Oncology', phase: '2', indication: 'NSCLC · KRAS G12C', geo: ['US', 'EU'],
      enrollment: '410', status: 'Ranking in progress', statusTone: 'evidence', updated: '14 min ago',
      stages: [
        { key: 'parsed', label: 'Parsed', state: 'done', detail: '268 chunks' },
        { key: 'brief', label: 'Brief Extracted', state: 'done', detail: '12 sections' },
        { key: 'queries', label: 'Queries Generated', state: 'done', detail: '6 groups' },
        { key: 'evidence', label: 'Evidence Retrieved', state: 'done', detail: '96 sources' },
        { key: 'kols', label: 'KOLs Extracted', state: 'done', detail: '41 candidates' },
        { key: 'ranked', label: 'Ranked', state: 'active', detail: 'Scoring 41…' },
        { key: 'moss', label: 'Indexed in Moss', state: 'pending', detail: 'Queued' },
        { key: 'review', label: 'Ready for Review', state: 'pending', detail: 'Pending' },
      ],
    },
    'NEU-AD-118': {
      id: 'NEU-AD-118', nct: 'NCT06••••552', run: 'run_6b9d77',
      title: 'A Phase 2 Study of an Anti-Amyloid Antibody in Early Alzheimer’s Disease',
      sponsor: 'Cortexa Therapeutics', phase: '2', indication: 'Early Alzheimer’s', geo: ['US'],
      enrollment: '720', status: 'Retrieving evidence', statusTone: 'evidence', updated: '3 h ago',
      stages: [
        { key: 'parsed', label: 'Parsed', state: 'done', detail: '301 chunks' },
        { key: 'brief', label: 'Brief Extracted', state: 'done', detail: '12 sections' },
        { key: 'queries', label: 'Queries Generated', state: 'done', detail: '7 groups' },
        { key: 'evidence', label: 'Evidence Retrieved', state: 'active', detail: '52 / ~110…' },
        { key: 'kols', label: 'KOLs Extracted', state: 'pending', detail: 'Pending' },
        { key: 'ranked', label: 'Ranked', state: 'pending', detail: 'Pending' },
        { key: 'moss', label: 'Indexed in Moss', state: 'pending', detail: 'Pending' },
        { key: 'review', label: 'Ready for Review', state: 'pending', detail: 'Pending' },
      ],
    },
    'IMM-PSO-330': {
      id: 'IMM-PSO-330', nct: 'NCT06••••907', run: null,
      title: 'A Phase 3 Study of an IL-23 Inhibitor in Moderate-to-Severe Plaque Psoriasis',
      sponsor: 'Aurelia Bio', phase: '3', indication: 'Plaque psoriasis', geo: ['EU', 'JP'],
      enrollment: '1,150', status: 'Queued', statusTone: 'neutral', updated: 'yesterday',
      stages: [
        { key: 'parsed', label: 'Parsed', state: 'pending', detail: 'Queued' },
        { key: 'brief', label: 'Brief Extracted', state: 'pending', detail: 'Pending' },
        { key: 'queries', label: 'Queries Generated', state: 'pending', detail: 'Pending' },
        { key: 'evidence', label: 'Evidence Retrieved', state: 'pending', detail: 'Pending' },
        { key: 'kols', label: 'KOLs Extracted', state: 'pending', detail: 'Pending' },
        { key: 'ranked', label: 'Ranked', state: 'pending', detail: 'Pending' },
        { key: 'moss', label: 'Indexed in Moss', state: 'pending', detail: 'Pending' },
        { key: 'review', label: 'Ready for Review', state: 'pending', detail: 'Pending' },
      ],
    },
  },

  // maps a sidebar screen to the stage that must be reached before it has data
  screenStage: { brief: 'brief', queries: 'queries', evidence: 'evidence', candidates: 'kols', ranking: 'ranked', compliance: 'review', moss: 'moss', summary: 'review' },

  // ---------------------------------------------------------------- voice agent (scoped per protocol)
  // Answers use [n] tokens that render as evidence citations. Grounded in the indexed data for RSV;
  // the in-flight protocols answer honestly from their current run state.
  voice: {
    'RSV-PreF-301': {
      suggestions: [
        'Why is Dr. Marchetti ranked #1?',
        'Which KOLs have direct Phase 3 trial experience?',
        'Draft a compliant MSL pre-call brief for Dr. Tanaka',
        'What compliance flags are open?',
      ],
      qa: [
        { q: 'Why is Dr. Marchetti ranked #1?',
          a: 'Dr. Elena Marchetti scores 92.4. She was coordinating principal investigator across 14 EU sites for the pivotal prefusion-F efficacy cohort[1] and first-authored the NEJM efficacy paper on the protocol’s primary LRTD endpoint in adults ≥60[2]. Trial experience (24/25) and protocol match (19.2/20) separate her from the field.',
          chips: [{ label: '3 citations', tone: 'evidence' }, { label: 'Guardrail check passed', tone: 'safe' }] },
        { q: 'Which KOLs have direct Phase 3 trial experience?',
          a: 'Two candidates hold a lead or investigator role on Phase 3 prefusion-F work: Dr. Marchetti (coordinating PI, 14 EU sites)[1] and Prof. Tanaka (national coordinating investigator, Japan immunogenicity sub-study)[2]. Dr. Okonkwo contributed to related guideline work but no pivotal trial role was found.',
          chips: [{ label: '2 citations', tone: 'evidence' }, { label: 'Ranked by scientific relevance only', tone: 'safe' }] },
        { q: 'Draft a compliant MSL pre-call brief for Dr. Tanaka',
          a: 'Generated a non-promotional pre-call brief for Prof. Hideo Tanaka — background, related Phase 3 trial experience[1], recent immunogenicity publications[2], and suggested scientific-exchange topics. Every claim is traced to source; no prescribing-volume or promotional content was included.',
          chips: [{ label: 'Guardrail check passed', tone: 'safe' }, { label: 'Non-promotional', tone: 'safe' }] },
        { q: 'What compliance flags are open?',
          a: 'Two open flags. High: a transparency / payment note on Dr. Grace Mwangi — an Open Payments consulting relationship in the indication that must be disclosed before outreach. Medium: Prof. Delacroix is below the 2-source evidence threshold for an evidence-backed recommendation. Both block final sign-off.',
          chips: [{ label: '2 open flags', tone: 'risk' }, { label: 'Audit-logged', tone: 'evidence' }] },
      ],
    },
    'ONC-KRAS-204': {
      suggestions: ['How many candidates so far?', 'When will ranking finish?', 'Show top evidence sources'],
      qa: [
        { q: 'How many candidates so far?',
          a: 'The run for ONC-KRAS-204 has extracted 41 KRAS G12C / NSCLC candidates from 96 evidence sources. Ranking is in progress now — I can give evidence-backed rationale once scoring completes.',
          chips: [{ label: 'Run in progress', tone: 'evidence' }] },
        { q: 'When will ranking finish?',
          a: 'Ranking is actively scoring all 41 candidates across the six relevance dimensions. The Moss index and review stages are queued behind it; nothing is held for manual review yet.',
          chips: [{ label: 'Ranking · active', tone: 'evidence' }] },
        { q: 'Show top evidence sources',
          a: 'Evidence retrieval completed with 96 sources across ClinicalTrials.gov, PubMed and congress pages. Detailed per-source views in this prototype are wired for RSV-PreF-301 — switch protocols to explore them.',
          chips: [{ label: 'Evidence · complete', tone: 'evidence' }] },
      ],
    },
    'NEU-AD-118': {
      suggestions: ['What stage is this run at?', 'How much evidence is collected?'],
      qa: [
        { q: 'What stage is this run at?',
          a: 'NEU-AD-118 is mid-evidence-retrieval — about 52 of an estimated 110 sources collected for early-Alzheimer’s anti-amyloid research. KOL extraction and ranking start once retrieval finishes.',
          chips: [{ label: 'Evidence · active', tone: 'evidence' }] },
        { q: 'How much evidence is collected?',
          a: '52 sources indexed so far and climbing. I’ll surface candidate experts and evidence-backed ranking as soon as the retrieval stage completes for this protocol.',
          chips: [{ label: 'Run in progress', tone: 'evidence' }] },
      ],
    },
    'IMM-PSO-330': {
      suggestions: ['Has processing started?'],
      qa: [
        { q: 'Has processing started?',
          a: 'IMM-PSO-330 is queued — parsing hasn’t begun, so there’s no protocol brief, evidence or KOL data to query yet. Start the run from the Protocols list and I’ll be able to answer once it’s indexed.',
          chips: [{ label: 'Queued', tone: 'neutral' }] },
      ],
    },
  },
};
